### ISSUE TITLE
Why streamlink

### ISSUE THREAD

**Issue by brkn** [HiDeoo/vod#1]
Hi Hideoo, I like your projects.

I'm just curious and want to learn, is there a reason you build it with `streamlink`, instead of `youtube-dl`? Does it work better with nodejs?

**Comment by HiDeoo** [comment]
Thanks 😄 

The reason is purely "me". I wanted a small CLI tool / UI to download some VODs for myself. I'm already using `streamlink` to watch Twitch streams in VLC instead of using the official website so I had it installed on my machine and knew it could download VODs so that was the go-to solution for me.

Both would work as I'm only spawning a new process using the `streamlink` command so it would work as well with `youtube-dl`. The command could even be parameterized or the tool could not use any 3rd party and download itself the VOD but I wanted to build this tool quickly and in a way it would fit my basic needs.
